-- Generated by drizzle-kit, reordered by hand: the UNIQUE constraints go before the foreign keys
-- that point at them (drizzle-kit wrote them after, and Postgres would reject the keys).
ALTER TABLE "commission_plans" ADD COLUMN "account_id" uuid;--> statement-breakpoint
ALTER TABLE "commission_plans" ADD COLUMN "category_id" uuid;--> statement-breakpoint
ALTER TABLE "transactions" ADD COLUMN "commission_payout_id" uuid;--> statement-breakpoint
ALTER TABLE "categories" ADD CONSTRAINT "categories_user_id_id_unique" UNIQUE("user_id","id");--> statement-breakpoint
ALTER TABLE "commission_payouts" ADD CONSTRAINT "commission_payouts_user_id_id_unique" UNIQUE("user_id","id");--> statement-breakpoint
ALTER TABLE "commission_plans" ADD CONSTRAINT "commission_plans_account_fk" FOREIGN KEY ("user_id","account_id") REFERENCES "public"."accounts"("user_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commission_plans" ADD CONSTRAINT "commission_plans_category_fk" FOREIGN KEY ("user_id","category_id") REFERENCES "public"."categories"("user_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_commission_payout_fk" FOREIGN KEY ("user_id","commission_payout_id") REFERENCES "public"."commission_payouts"("user_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "transactions_commission_payout_id_unique" ON "transactions" USING btree ("commission_payout_id");--> statement-breakpoint
ALTER TABLE "commission_plans" ADD CONSTRAINT "commission_plans_income_target" CHECK (("commission_plans"."account_id" is null) = ("commission_plans"."category_id" is null));--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_commission_payout_income" CHECK ("transactions"."commission_payout_id" is null or "transactions"."kind" = 'income');