// Applies the SQL generated by drizzle-kit to one schema (`app`, `app_dev`, or a test schema).
// Shared by scripts/db-migrate.js (Node, real database) and the tests (PGlite), so it has no imports
// and only uses TypeScript syntax that Node can strip.

export interface Migration {
  /** File name without extension, e.g. `0000_create_profiles`. */
  name: string
  sql: string
}

/** The subset of `pg.Client` and `PGlite` used here. */
export interface SqlClient {
  query(text: string, params?: unknown[]): Promise<{ rows: unknown[] }>
}

const SCHEMA_NAME = /^[a-z_][a-z0-9_]*$/
const STATEMENT_BREAKPOINT = '--> statement-breakpoint'

/** Hash of a migration file; line endings are normalized so a CRLF checkout does not change it. */
async function sha256(text: string) {
  const bytes = new TextEncoder().encode(text.replaceAll('\r\n', '\n'))
  const digest = await crypto.subtle.digest('SHA-256', bytes)
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join('')
}

/**
 * drizzle-kit writes foreign keys as `REFERENCES "public"."table"`. Removing the qualifier lets the
 * search_path set below decide the schema. Nothing of ours lives in `public`.
 */
function statementsOf(sql: string) {
  return sql
    .split(STATEMENT_BREAKPOINT)
    .map((statement) => statement.replaceAll('"public".', '').trim())
    .filter(Boolean)
}

/**
 * Applies the pending migrations, in name order and in a single transaction: either all of them are
 * applied or none. Refuses to run if an applied migration changed or disappeared, or if a pending
 * one sorts before the last applied one. Returns the names it applied.
 */
export async function migrate(db: SqlClient, schema: string, migrations: Migration[]) {
  if (!SCHEMA_NAME.test(schema)) throw new Error(`Nombre de schema no válido: ${schema}`)
  const sorted = [...migrations].sort((a, b) => a.name.localeCompare(b.name))

  await db.query('begin')
  try {
    const { rows: found } = await db.query('select 1 from pg_namespace where nspname = $1', [
      schema,
    ])
    if (found.length === 0) {
      throw new Error(`El schema ${schema} no existe. Créalo antes con scripts/bootstrap-db.sql.`)
    }

    // Kept out of the app schemas: the API roles cannot read or change it.
    await db.query('create schema if not exists migrations')
    await db.query(`
      create table if not exists migrations.history (
        schema_name text not null,
        name text not null,
        hash text not null,
        applied_at timestamptz not null default now(),
        primary key (schema_name, name)
      )`)
    // Serializes concurrent runs (e.g. two deploys); released at commit or rollback.
    await db.query('lock table migrations.history in exclusive mode')
    await db.query(`set local search_path to ${schema}`)

    const { rows } = await db.query(
      'select name, hash from migrations.history where schema_name = $1 order by name',
      [schema],
    )
    const applied = rows as { name: string; hash: string }[]
    const byName = new Map(sorted.map((migration) => [migration.name, migration]))
    for (const { name, hash } of applied) {
      const migration = byName.get(name)
      if (!migration) {
        throw new Error(
          `La migración ${name} está aplicada en ${schema} pero no está en el repositorio.`,
        )
      }
      if ((await sha256(migration.sql)) !== hash) {
        throw new Error(`La migración ${name} cambió después de aplicarse en ${schema}.`)
      }
    }

    const appliedNames = new Set(applied.map(({ name }) => name))
    const lastApplied = applied.at(-1)?.name
    const pending = sorted.filter(({ name }) => !appliedNames.has(name))
    for (const migration of pending) {
      if (lastApplied && migration.name < lastApplied) {
        throw new Error(
          `La migración ${migration.name} va antes de ${lastApplied}, que ya está aplicada. Renómbrala.`,
        )
      }
      for (const statement of statementsOf(migration.sql)) await db.query(statement)
      await db.query(
        'insert into migrations.history (schema_name, name, hash) values ($1, $2, $3)',
        [schema, migration.name, await sha256(migration.sql)],
      )
    }

    await db.query('commit')
    return pending.map(({ name }) => name)
  } catch (err) {
    await db.query('rollback')
    throw err
  }
}
